export * from './Cat_Components/Cats'
export * from './Cat_Components/Cat'
export * from './Cat_Components/FormCat'
export * from './Dog_Components/Dog'
export * from './Dog_Components/Dogs'
export * from './Dog_Components/FormDog'